networks:
  hotel_network:
    driver: bridge

services:
  neredekal.hotel.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  neredekal.rapor.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5002
      - ASPNETCORE_HTTPS_PORTS=5002
    ports:
      - "5002:5002"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - hotel_network

  neredekal.rapor.consumer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=6002
      - ASPNETCORE_HTTPS_PORTS=6002
    ports:
      - "6002:6002"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - hotel_network

  hoteldb:
    image: postgres
    container_name: hoteldb
    environment:
    - POSTGRES_DB=hotelDb
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    volumes:
    - ./.containers/database:/var/lib/postgresql/data
    ports:
    - 5430:5432
    networks:
      - hotel_network

  reportdb:
    image: postgres
    container_name: reportdb
    environment:
    - POSTGRES_DB=ReportDb
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    volumes:
    - ./.containers/database:/var/lib/postgresql/data
    ports:
    - 5431:5432
    networks:
      - hotel_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: RabbitMq
    hostname: rabbitmq
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/log/rabbitmq  
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - hotel_network

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    networks:
      - hotel-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - hotel-network
