// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neredekal.Hotel.Insfrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Neredekal.Hotel.Insfrastructure.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Neredekal.Hotel.Domain.AggregateModels.HotelModels.Hotel", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UUID");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("Neredekal.Hotel.Domain.AggregateModels.HotelModels.HotelContactInfoItems", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<string>("InformationContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InformationType")
                        .HasColumnType("integer");

                    b.HasKey("UUID");

                    b.HasIndex("HotelId");

                    b.ToTable("HotelContactInfoItems");
                });

            modelBuilder.Entity("Neredekal.Hotel.Domain.AggregateModels.HotelModels.HotelContactInfoItems", b =>
                {
                    b.HasOne("Neredekal.Hotel.Domain.AggregateModels.HotelModels.Hotel", "Hotel")
                        .WithMany("HotelContactInfoItems")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Neredekal.Hotel.Domain.AggregateModels.HotelModels.Hotel", b =>
                {
                    b.Navigation("HotelContactInfoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
